
Use BDSeg




CREATE TABLE Usuario (
    Id_Usuario BIGINT IDENTITY(1,1) PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Contrasenia VARCHAR(200) NOT NULL,
    Nombres VARCHAR(100) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    DNI VARCHAR(8) NOT NULL UNIQUE,
    Telefono VARCHAR(9) NULL,
    Img_Perfil VARCHAR(200) NULL,
    Correo VARCHAR(100) NULL,
    Rol VARCHAR(20) CHECK (Rol IN ('ADMINISTRADOR', 'RECEPCIONISTA', 'CAJERO')) NOT NULL
);
